version: '3.8'

services:

  hublinks:
    image: luiscruzcwb00/hublinks:latest
    container_name: hublinks-page
    restart: unless-stopped
    volumes:
      - ./css:/usr/share/nginx/html/css
      - ./font:/usr/share/nginx/html/font
      - ./img:/usr/share/nginx/html/img
      - ./js:/usr/share/nginx/html/js
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - 80:80
    environment:
      - TZ=America/Sao_Paulo